package com.giorgiolupo.theodds;

import android.content.Context;
import android.content.Intent;
import android.widget.Toast;

import androidx.annotation.NonNull;

import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.ValueEventListener;

public class CreateOnlineChallengeDB extends ChallengeDB {
    String uniqueId;

    //constructor
    public CreateOnlineChallengeDB(Context context) {
        super(context);
    }

    //create dares
    public void createChallengeDB(String dareText, String challenger, String receiver) {
        DatabaseReference databaseReference = firebaseDatabase.getReference("challenges");
        databaseReference.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(@NonNull DataSnapshot snapshot) {
                // Generate a reference to a new location and add some data using push()
                DatabaseReference pushedPostRef = databaseReference.push();
                // Get the unique ID generated by a push()
                uniqueId = pushedPostRef.getKey();
                //push the text of challenge
                pushedPostRef.child("text").setValue(dareText);

                Auth auth = new Auth(context);
                FirebaseAuth mAuth = FirebaseAuth.getInstance();
                Toast.makeText(context, mAuth.getCurrentUser().getUid(), Toast.LENGTH_SHORT).show();


                //push values into DB
                pushedPostRef.child("step").setValue("2");
                pushedPostRef.child("challenger_name").setValue(challenger);
                pushedPostRef.child("receiver_name").setValue(receiver);
                pushedPostRef.child("challenger_id").setValue(auth.getCurrentUser());
                pushedPostRef.child("receiver_id").setValue("x");

                //share challege with friends
                shareDare(uniqueId);


            }

            @Override
            public void onCancelled(@NonNull DatabaseError error) {
            }
        });
    }



    //share with friends
    private void shareDare(String uniqueId) {
        Intent sendIntent = new Intent();
        sendIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        sendIntent.setAction(Intent.ACTION_SEND);
        sendIntent.putExtra(Intent.EXTRA_TEXT,
                "https://giorgiolupo.page.link/H3Ed/?id=" + uniqueId);
        sendIntent.setType("text/plain");
        Intent shareIntent = Intent.createChooser(sendIntent, null);
        shareIntent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
        context.startActivity(shareIntent);
    }

    //create node for users
}
